
billboards:
  billboard2:
    width: 6
    height: 5
    material: BLACK_CONCRETE
    image: "billboard2.png"
  
  billboard1:
    width: 8
    height: 6
    material: BLACK_CONCRETE
    image: "billboard1.png"
  
  billboard0:
    width: 10
    height: 8
    material: GRAY_CONCRETE
    image: "billboard0.png"

# Visual effects settings
effects:
  glow_when_looking: true
  glow_color: GREEN
  look_range: 32
  dithering: floyd_steinberg
